from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from io import BytesIO
from typing import Optional

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.schemas.meeting_summary import MeetingSummary


@dataclass(frozen=True)
class WordExportMetadata:
    original_filename: Optional[str] = None
    llm_provider: Optional[str] = None
    generated_at: Optional[datetime] = None


def build_docx_from_summary(
    summary: MeetingSummary,
    transcript: str | None,
    meta: WordExportMetadata,
) -> bytes:
    doc = Document()

    _add_title(doc, "Meeting Notes")
    _add_subtitle(
        doc,
        original_filename=meta.original_filename,
        llm_provider=meta.llm_provider,
        generated_at=meta.generated_at or datetime.now(timezone.utc),
    )

    _add_section_heading(doc, "Executive Summary")
    _add_paragraph_or_fallback(doc, summary.meeting_summary, "No summary available.")

    _add_section_heading(doc, "Participants")
    _add_bullets_or_fallback(doc, summary.participants, "Not identified.")

    _add_section_heading(doc, "Decisions")
    _add_numbered_or_fallback(doc, summary.decisions, "No explicit decisions found.")

    _add_section_heading(doc, "Action Items")
    _add_action_items_table(doc, summary)

    doc.add_paragraph()
    note = doc.add_paragraph("Note: This document was generated by AI and may contain inaccuracies.")
    note.runs[0].font.size = Pt(9)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _add_title(doc: Document, text: str) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(20)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER


def _add_subtitle(
    doc: Document,
    original_filename: Optional[str],
    llm_provider: Optional[str],
    generated_at: datetime,
) -> None:
    parts = []
    if original_filename:
        parts.append(f"File: {original_filename}")
    if llm_provider:
        parts.append(f"LLM: {llm_provider}")
    parts.append(f"Generated: {generated_at.astimezone(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")

    p = doc.add_paragraph(" | ".join(parts))
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if p.runs:
        p.runs[0].font.size = Pt(10)


def _add_section_heading(doc: Document, title: str) -> None:
    doc.add_paragraph()
    h = doc.add_paragraph()
    run = h.add_run(title)
    run.bold = True
    run.font.size = Pt(14)


def _add_paragraph_or_fallback(doc: Document, text: Optional[str], fallback: str) -> None:
    content = (text or "").strip()
    doc.add_paragraph(content if content else fallback)


def _add_bullets_or_fallback(doc: Document, items: list[str], fallback: str) -> None:
    if not items:
        doc.add_paragraph(fallback)
        return
    for x in items:
        v = (x or "").strip()
        if v:
            doc.add_paragraph(v, style="List Bullet")


def _add_numbered_or_fallback(doc: Document, items: list[str], fallback: str) -> None:
    if not items:
        doc.add_paragraph(fallback)
        return
    for x in items:
        v = (x or "").strip()
        if v:
            doc.add_paragraph(v, style="List Number")


def _add_action_items_table(doc: Document, summary: MeetingSummary) -> None:
    items = summary.action_items or []
    if not items:
        doc.add_paragraph("No action items found.")
        return

    table = doc.add_table(rows=1, cols=4)
    hdr = table.rows[0].cells
    hdr[0].text = "Task"
    hdr[1].text = "Owner"
    hdr[2].text = "Due date"
    hdr[3].text = "Priority"

    for it in items:
        row = table.add_row().cells
        row[0].text = (getattr(it, "task", None) or "").strip() or "-"
        row[1].text = (getattr(it, "owner", None) or "").strip() or "-"
        row[2].text = (getattr(it, "due_date", None) or "").strip() or "-"
        row[3].text = (getattr(it, "priority", None) or "").strip() or "-"
